name: Project 2 CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Validate application
        run: python -m py_compile app.py
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::<610519500341>:role/project2-github-actions-role
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity